apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-ingress
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-01-17T12:16:44Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.12.0
    helm.sh/chart: ingress-nginx-4.12.0
  name: nginx-ingress-ingress-nginx-controller
  namespace: default
  resourceVersion: "80962"
  uid: 41c3400c-c07f-49fa-ae16-b87f2366c4b3
spec:
  externalIPs:
  - 192.168.0.163
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.199.228
  clusterIPs:
  - 10.96.199.228
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 32074
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 31379
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: nodePort
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.163
      ipMode: VIP
